### ISSUE TITLE
Level 2 skipped, when converting

### ISSUE THREAD

**Issue by JasperChecksum** [b0g3r/plantuml2freemind#32]
When I convert this, the result skips level 2.

![grafik](https://user-images.githubusercontent.com/51070645/104915423-e958b680-5990-11eb-8456-5e64f5a2db86.png)

![grafik](https://user-images.githubusercontent.com/51070645/104915231-a565b180-5990-11eb-986d-0ae4836d0b93.png)

I this intended (left/right node concept) or an issue?

**Comment by b0g3r** [comment]
It looks like an issue. I reproduced with
```plantuml
@startmindmap
* first
** second
*** third
**** fourth
@endmindmap
```

Also, I think the problem somewhere around .mm converter, because .yaml generated correctly:
```yaml
text: first
link: null
style: bubble
color: null
right:
  text: second
  link: null
  style: bubble
  color: null
  children:
  - text: third
    link: null
    style: bubble
    color: null
    children:
    - text: fourth
      link: null
      style: bubble
      color: null
      children: []
left: null
```
